// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13IVi4aRhEGsfHa0rSiRAu6PC7QiOSWk',
    appId: '1:979667025150:web:4810225fe85a3b97fe39af',
    messagingSenderId: '979667025150',
    projectId: 'chatcine-890d1',
    authDomain: 'chatcine-890d1.firebaseapp.com',
    storageBucket: 'chatcine-890d1.appspot.com',
    measurementId: 'G-MTR09HYCNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN-nZzvWkMwJVypFJFObwEytbPOmmnR24',
    appId: '1:979667025150:android:7ca12c3148269253fe39af',
    messagingSenderId: '979667025150',
    projectId: 'chatcine-890d1',
    storageBucket: 'chatcine-890d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWcgRZorb4Vx9YkVTKmMGiaL120P-Bgu4',
    appId: '1:979667025150:ios:c40904a047ec7bb8fe39af',
    messagingSenderId: '979667025150',
    projectId: 'chatcine-890d1',
    storageBucket: 'chatcine-890d1.appspot.com',
    androidClientId: '979667025150-iau66mbrkg847a6ulfjrrdv677btlinq.apps.googleusercontent.com',
    iosClientId: '979667025150-hr19si0dgb63amg2lt32cgj39al0cibl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatcine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWcgRZorb4Vx9YkVTKmMGiaL120P-Bgu4',
    appId: '1:979667025150:ios:c40904a047ec7bb8fe39af',
    messagingSenderId: '979667025150',
    projectId: 'chatcine-890d1',
    storageBucket: 'chatcine-890d1.appspot.com',
    androidClientId: '979667025150-iau66mbrkg847a6ulfjrrdv677btlinq.apps.googleusercontent.com',
    iosClientId: '979667025150-hr19si0dgb63amg2lt32cgj39al0cibl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatcine',
  );
}
